services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  express-server:
    build:
      context: .
      dockerfile: apps/express-server/Dockerfile
    ports:
      - '4000:4000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - BETTER_AUTH_SECRET=your-secret-here
      - BETTER_AUTH_URL=http://localhost:4000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/express-server:/app/apps/express-server
      - /app/apps/express-server/node_modules
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '5173:5173'
    environment:
      - VITE_AUTH_BASE_URL=http://localhost:4000
    volumes:
      - ./apps/web:/app/apps/web
      - /app/apps/web/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
